// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnxtcsflhqxwcxmhgtiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpueHRjc2ZsaHF4d2N4bWhndGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODg0MTUsImV4cCI6MjA3MzE2NDQxNX0.cci0aD2IfmamHpTAT3P6ll7r2q8nVrihgcY7qsoO2tM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});